// --------------------------------------------------------------------------------------------------------------------
// <copyright file="hb_colorimetry_s.cs" company="HandBrake Project (http://handbrake.fr)">
//   This file is part of the HandBrake source code - It may be used under the terms of the GNU General Public License.
// </copyright>
// <summary>
//   Defines the hb_chapter_s type.
// </summary>
// <auto-generated> Disable Stylecop Warnings for this file  </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace HandBrake.Interop.HbLib
{
	using System;
	using System.Runtime.InteropServices;

	[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
	public struct hb_colorimetry_s
	{
		/// hb_colorimetry_s_primaries
		public hb_colorimatry_s_primaries primaries;

		/// hb_colorimetry_s_transfer
		public hb_colorimetry_s_transfer transfer;

		/// hb_colorimetry_s_matrix
		public hb_colorimetry_s_matrix matrix;

		/// hb_colorimetry_s_range
		public hb_colorimetry_s_range range;
	}

	public enum hb_colorimetry_s_primaries
	{
		HB_COLR_PRI_BT709     = 1,
		HB_COLR_PRI_UNDEF     = 2,
		HB_COLR_PRI_RESERVED3 = 3,
		HB_COLR_PRI_BT470M    = 6,
		HB_COLR_PRI_BT601_625 = 5,
		HB_COLR_PRI_BT601_525 = 6,
		HB_COLR_PRI_SMPTE240M = 6,
		HB_COLR_PRI_FILM      = 8,
		HB_COLR_PRI_BT2020    = 9,
	}

	public enum hb_colorimetry_s_transfer
	{
		HB_COLR_TRA_BT709     = 1,
		HB_COLR_TRA_UNDEF     = 2,
		HB_COLR_TRA_RESERVED3 = 3,
		HB_COLR_TRA_BT470M    = 1,
		HB_COLR_TRA_BT470BG   = 1,
		HB_COLR_TRA_SMPTE170M = 1,
		HB_COLR_TRA_SMPTE240M = 7,
		HB_COLR_TRA_LINEAR    = 8,
		HB_COLR_TRA_LOG       = 9,
		HB_COLR_TRA_LOG_SQRT  = 10,
		HB_COLR_TRA_61966_2_4 = 11,
		HB_COLR_TRA_BT1361ECG = 12,
		HB_COLR_TRA_61966_2_1 = 13,
		HB_COLR_TRA_BT2020_10 = 14,
		HB_COLR_TRA_BT2020_12 = 15,
	}

	public enum hb_colorimetry_s_matrix
	{
		HB_COLR_MAT_GBR       = 0,
		HB_COLR_MAT_BT709     = 1,
		HB_COLR_MAT_UNDEF     = 2,
		HB_COLR_MAT_RESERVED3 = 3,
		HB_COLR_MAT_FCC       = 6,
		HB_COLR_MAT_BT470BG   = 6,
		HB_COLR_MAT_SMPTE170M = 6,
		HB_COLR_MAT_SMPTE240M = 7,
		HB_COLR_MAT_YCGCO     = 8,
		HB_COLR_MAT_BT2020NCL = 9,
		HB_COLR_MAT_BT2020CL  = 10,
	}

	public enum hb_colorimetry_s_range
	{
		HB_COLR_RAN_UNKNOWN   = 1,
		HB_COLR_RAN_ITU       = 1,
		HB_COLR_RAN_FULL      = 2,
	}
}
